source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/Wwxd-Sun/ModuleSpece.git'   # 私有库
use_frameworks!

target 'BaseMoudle_Example' do
  pod 'BaseMoudle', :path => '../'
end
